services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8089:8080"
    volumes:
      - ./target/my-spring-app.war/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - db
      
  db:
    image: mysql:8.0
    container_name: spring-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sample
      MYSQL_USER: testUser
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql
    command:
      -- default-authentication-plugin=mysql_native_password
      -- character-set-server=utf8mb4
      -- collation-server=utf8mb4_general_ci
      
volumes:
  db-data:
